### ISSUE TITLE
EMC not synchronized after Server restart

### ISSUE THREAD

**Issue by 4w3Official** [yzl210/TeamProjectE#1] opened 2022-11-16 22:41 UTC
If the team leader is offline and the server restarts e.g. after a crash or reboot, the entire EMC is at 0 and all progress in the Transmutation table is gone.

Modpack: `FTB StoneBlock 3` _(added later)_
Filename: `teamprojecte-1.18.2-1.0.jar`

**Comment by yzl210** [comment] 2023-03-04 09:42
Sorry for not getting back to you sooner... was pretty busy with school.
I can't seem to reproduce this issue in a clean environment (Only with ProjectE and Project Expansion).
Are there any detailed steps to reproduce it?

**Comment by yzl210** [comment] 2023-07-01 11:42
Closing it since there is not enough information

**Comment by joklbash** [comment] 2023-07-14 09:53
I can provide the details on how this happens. 

After a server restart, if the team leader isn't the first person to log back in, EMC is 0 for all party members. If the team leader logs in first, everything is ok until the next server restart.

Maybe EMC is stored in the leaders profile instead of the world?

At any rate, this is a great mod and after so many years, answered the need of SMP support for us. Ty!

**Comment by yzl210** [comment] 2023-07-14 12:58
> Maybe EMC is stored in the leaders profile instead of the world?

No, it's stored inside the data folder of the world.

**Comment by yzl210** [comment] 2023-07-14 13:01
> After a server restart, if the team leader isn't the first person to log back in, EMC is 0 for all party members. If the team leader logs in first, everything is ok until the next server restart.

I tested again and still can't reproduce this with only ProjectE, this mod, and Project Expansion.

What mods are you using?

**Comment by joklbash** [comment] 2023-07-14 13:08
I was in StoneBlock 3 (only added this mod). Give me a bit and I'll build up a server with just the ProjectE stuff in it. I never had an issue until the server reboot, no matter how many times we logged in/out or who logged in/out once things were working. Also had the same issue in Vault Hunters 3 (adding ProjectE and this mod).

**Comment by yzl210** [comment] 2023-07-14 14:00
It's weird that both of you are playing Stoneblock 3

**Closed as not planned** 2023-08-25 17:34 UTC
Labels: can't reproduce, needs more information
